apiVersion: v1
kind: ServiceAccount
metadata:
  name: redirect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redirect
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redirect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redirect
subjects:
  - kind: ServiceAccount
    name: redirect
    namespace: lightpath-system
