---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redirect
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redirect
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redirect
    spec:
      hostNetwork: true # required
      serviceAccountName: redirect
      volumes:
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
        - hostPath:
            path: /lib/modules
          name: lib-modules
      containers:
        - image: ghcr.io/xvzf/lightpath/redirect:latest
          imagePullPolicy: Always
          args:
          - -v=3
          name: redirect
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /lib-modules
              name: lib-modules
              readOnly: true
          securityContext:
            # readOnlyRootFilesystem: true
            privileged: true
            # capabilities:
            #   drop:
            #     - all
            #   add:
            #     - CAP_NET_ADMIN
      tolerations:
        - operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/pid-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists
