---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redirect
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redirect
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redirect
    spec:
      hostNetwork: true # required
      serviceAccountName: redirect
      volumes:
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
      containers:
        - image: ghcr.io/xvzf/lightpath/redirect:latest
          name: redirect
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
          securityContext:
            # readOnlyRootFilesystem: true
            privileged: true
            # capabilities:
            #   drop:
            #     - all
            #   add:
            #     - CAP_NET_ADMIN
