---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controlplane
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: controlplane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controlplane
    spec:
      hostNetwork: true # required
      serviceAccountName: controlplane
      containers:
        - image: ghcr.io/xvzf/lightpath/controlplane:latest
          name: controlplane
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - --metric-port=9000
            - --host="127.0.0.1:18000"
            - --nodeID=$(NODE_NAME)
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 150Mi
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: proxy-config
