apiVersion: v1
kind: ServiceAccount
metadata:
  name: controlplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlplane
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - watch
  - apiGroups:
      - discovery/v1
    resources:
      - endpointslices
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controlplane
subjects:
  - kind: ServiceAccount
    name: controlplane
    namespace: lightpath-system
