---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opa-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server
spec:
  secretName: webhook-server-tls
  dnsNames:
    - webhook-server
    - webhook-server.lightpath-system.svc
    - webhook-server.lightpath-system.svc.cluster
    - webhook-server.lightpath-system.svc.cluster.local
  issuerRef:
    name: opa-selfsigned
---
apiVersion: v1
kind: Service
metadata:
  name:
    webhook-server
spec:
  selector:
    app.kubernetes.io/name: webhook-server
  ports:
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webhook-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: webhook-server
  name: webhook-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-server
      name: webhook-server
    spec:
      containers:
        - image: openpolicyagent/opa:0.41.0-static
          name: opa
          ports:
            - name: https
              containerPort: 8443
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:8443"
            - "--set=status.console=true"
            - "--set=decision_logs.console=true"
            - "--log-format=json"
            - "--format=pretty"
            - "--watch"
            - "/policies"
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: server-cert
            - readOnly: true
              mountPath: /policies
              name: policies
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 96Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              port: https
              scheme: HTTPS
              path: /health
          readinessProbe:
            httpGet:
              port: https
              scheme: HTTPS
              path: /health?plugins&bundle
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
      volumes:
        - name: policies
          configMap:
            name: policies
        - name: server-cert
          secret:
            secretName: webhook-server-tls
