---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        prometheus.io/port: "15000"
    spec:
      hostNetwork: true # required
      serviceAccountName: proxy
      containers:
        - image: envoyproxy/envoy:v1.22-latest
          name: envoy
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - -c
            - /config/envoy.yaml
            - --service-node
            - $(NODE_NAME)
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: config
          ports:
            - name: admin-http
              containerPort: 15000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 150Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              port: admin-http
              path: /ready
          readinessProbe:
            httpGet:
              port: admin-http
              path: /ready
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534
      volumes:
        - name: config
          configMap:
            name: proxy-config
      tolerations:
        - operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/pid-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
          operator: Exists
