---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# We'll run two proxies, but are replacing the functionality for some kube-proxy services so we can do
# comparitive benchmarks on a single cluster
# networking:
  # kubeProxyMode: "none"  # we are replacing kube-proxy
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker